### ISSUE TITLE
Can the speed be increased ?

### ISSUE THREAD

**Issue by oijkn** [ldbglobe/gitlab-finder#1]
We use a self-hosted Gitlab server and when I use your script to search for a word, the execution time is quite long between each project.

Is it possible to increase the number of concurrent requests ? Or something like that.

**Comment by ldbglobe** [comment]
I just add a new .env parameter allowing to reduce the delay between search.
*On official Gitlab server I still recommand the 6s delay*

see commit bbc7eb55db7590f3bce67d7ca098035d0d4d53c9
